### ISSUE TITLE
Access to XMLHttpRequest at 'http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=MwHlTiI' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy

### ISSUE THREAD

**Issue by oxamabaig** [maitrungduc1410/public-channel-realtime-chat#2]
Hello,
Can someone help me to get through this error? I successfully have run the directory but everytime to recieve new messages i need to referesh the browser. And when i check my console then i got this error.
![image](https://user-images.githubusercontent.com/35566773/69402321-4dde9e00-0d19-11ea-8fd1-31b9cc046cdd.png)

**Comment by maitrungduc1410** [comment]
I see that you're trying to call socket.io directly from 127.0.0.1. But it should run on port 6001 (default port of Laravel echo server). Please go to `resources/js/bootstrap.js` check that the `host` of Laravel echo is runing on the same port which you config in `laravel-echo-server.json`

**Comment by sinnguyen4991** [comment]
Chào anh, 


Em cũng bị lỗi tương tự.
Em đang chạy site `http://127.0.0.1:8000`

<img width="1141" alt="error" src="https://user-images.githubusercontent.com/37407310/79124074-c24bd380-7dc5-11ea-892d-1c40a2c21381.png">

anh có thể giải thích giúp em lỗi này là vì sao k ạ 
Thank anh

**Comment by maitrungduc1410** [comment]
lỗi này của bạn là do lúc chạy `laravel-echo-server init` bạn ko cho phép `CORS`. Bạn chạy lại `laravel-echo-server init` hoặc nếu ko thì thêm vào file `laravel-echo-server.json` đoạn sau nhé:
```json
"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "http://localhost:8000",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
```

Đổi xong nhớ chạy lại `laravel-echo-server start` nhé bạn

**Comment by sinnguyen4991** [comment]
Tuyệt vời anh ơi.
Đúng như anh nói,  do em chạy `127.0.0.1:8000` nên không khớp với `http://localhost:8000` nên gây ra lỗi. 

Cảm ơn anh đã support  rất nhanh và tận tình.

Chúc anh có buổi tối vui vẻ

**Comment by maitrungduc1410** [comment]
oke e nhé, chúc e vượt qua dịch bệnh :))
